### ISSUE TITLE
Comprehensive documentation

### ISSUE THREAD

**Issue by mtijas** [mtijas/examples#15]
### Description

Comprehensive documentation is needed to explain what, why and how this agile workflow could (should?) be used. Documentation should be written in the `example` repository wiki.

### Scope

The documentation should contain descriptions of different parts of the example, their suggested uses, relationships between these parts and relevant examples.

### Definition of Done

- [ ] Main README.md in `example` repository contains descriptions of the repositories and project views related.
- [ ] The wiki contains table of contents page (landing page).
- [ ] Themes are explained in the wiki.
- [ ] Epics are explained in the wiki.
- [ ] User stories are explained in the wiki.
- [ ] Issues are explained in the wiki.
- [ ] The kanban project view (workflow) is explained in the wiki.
- [ ] The relationships between themes, epics, user stories and issues are explained in the wiki.
- [ ] The data flow from ideas and themes to issues should be visualized somehow.
